placeholders:
  some-greeting-message:
    ru: 'Привет!'
    en: 'Hello!'
default-locale: 'ru'
languages:
  ru:
    display-name: 'Выбрать русский язык'
    value: 'ewogICJ0aW1lc3RhbXAiIDogMTY0NTg5NjAwNjc5NywKICAicHJvZmlsZUlkIiA6ICJlZDUzZGQ4MTRmOWQ0YTNjYjRlYjY1MWRjYmE3N2U2NiIsCiAgInByb2ZpbGVOYW1lIiA6ICI0MTQxNDE0MWgiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzE4NWViZjIxNTE2MTg3OTgxOTYzNzJhMjZlZjliMGM5NDg5NTM5MzcxNzM0NWFmODU0ZjgxZjBiZmVjOWZiIgogICAgfQogIH0KfQ=='
    signature: 'lzsHxJQ8bSu5OG9Yfr1pyY89wdst3GL1HD4qm9bcDZZ2bWqqXIjrEc4dUqzWFbO+869hvDmEMiIrXrDvWyjKUrcEO+g3ta5BHxvUJIr9+MOjtpL1cIeQd8KG1xHIA9MZT/G9sHBx2olIo3veJtbU0LnO/R9ed1K1M2w8T+EPk6iCzu5Jmg/GRb2AcHT7POBGdu0JIPRFWwBAoZsmWA0QIhqSB5UuDwXRLR1gReBBc2fNVDIOZFnDzIZgymV3Li7FAFARqtKyj1ckTU+/bpLZu0EKm8R1HQx22ZZR1fIWE5Df9Wfq8jbjRid6tTJDqsB0Jx5ITrUUNDz8zgDkXzygvW4qIEW7eKTomKX7/+BQwPNyczdBcu8Cyvs/iXnmfoa6MGtgjk6ApbObq93XCj9t+gKNIcV+Le50F0aZVoIrHlPbTlXCDDyWLEDHMsJxlBnsuPvPAj1FjUMrAUeknqTLlhxGqL88MWL5Lmng3iB/icRgw8crNFb5lJskbddTfGHrJmY45G1VVcaB9Se1t7Va76BCleqKvnj7dkdqSNwoCYoqrxM++xS6IwOuAxrs71uCuBEGI08/SOzfcLWfwxAeAXq1F7okzHT37pagpieJuB1iBRdhWu+HZM2Kb6XdXnMwAPzqtjeDe/NPAMjh6oAFIccmJmUEpfoRIn1xja6vIAg='
  en:
    display-name: 'Choose english language'
    value: 'ewogICJ0aW1lc3RhbXAiIDogMTcwNjM1NzY3NzA3NCwKICAicHJvZmlsZUlkIiA6ICJmOGJmNDBjOWExYzY0ZTllOTIyZTc4M2UwMzNiODBiMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJUeGxvbjUiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGI4ZWY2N2IxNGYyZjgyNTljMTUxM2ZmZmIxZWVlNjZlNDlmOTdlYWJlZDBkOWFhOWQ2ZWFkYmU5ZmU4Y2UxYSIKICAgIH0KICB9Cn0='
    signature: 'Uf9DGKKTOvBN+gMJGsyHP/D0Uu3YpvJZ04rWLvJCn5ukuoUQDnyhZr/EZuVpnxgkuH/VZ7Jo8CFznUrh2sP38SJx3eM1BGuMRg1nGY8xB6xoUVMRhSZgsTDpwnRLeFjNye1OMRz7GmTPCU4FrZ2d/uatzKvzsDOQAtfLkvU+xgy8SRUy14a75mgnJEj/Gzws7qfzI41cVPB+EYaLsXwGDAMzcqXnSAlVTDgaqdiTl/7Y9YLewiBLXrNzRJnD4psHda74AFqSi807Ef4iG2KsJ6a2WKBwh1OO3wZLNUG61VGhIq5ZlnBHx8gAZzTDzN1pY6ZaSpXxrEp3Pj/eBEtDJIMGeozxV4G0Mhamv46nNtIG+vFXE2qjkaf/hA8lWdaD6G4C0aRB6mK9BNcD/EDA5ngSO1L1uFyakwq3CqPTcybRfoBqI4x0bVn25ro0RJkDSNMlIl2WIOMa+pMllwMbmi5rgLhX6UQZCVoNNiOyC3tqLcxMi0C3gQx2ushl7FyiezXgI2fLHPeGuXvh1daYOlaiox4enebKCWRL7/+fIjs7uHAjQaEbpdKMfRRWlfKbOS+EhNTEzgBciNp3N7L+4gM3nI4OYja/QcMwiUrHUgKrVpP4YVAON1C+gnbxDfihp9TqkjnxJRVPcs1LG4rzaUtyQzHF4OF30hPfx0NJyl4='
create-table-if-does-not-exist: false
lang-command:
  check-permission: false
  permission: 'bilang.lang'
sql-queries:
  create-table: 'CREATE TABLE IF NOT EXISTS players(name VARCHAR(16) PRIMARY KEY, locale VARCHAR(4));'
  create: 'INSERT INTO players(name, locale) VALUES(?, ?);'
  read: 'SELECT locale FROM players WHERE name = ?;'
  update: 'UPDATE players SET locale = ? WHERE name = ?;'
  delete: 'DELETE FROM players WHERE name = ?;'
db:
  url: 'jdbc:mysql://localhost:3306/test'
  username: 'root'
  password: 'root'